#ifndef __INCLUDE_WAVEBANK_WAVEBANK__
#define __INCLUDE_WAVEBANK_WAVEBANK__

typedef enum
{
    XACT_WAVEBANK_WAVEBANK_BANG1 = 0,
    XACT_WAVEBANK_WAVEBANK_BANG2 = 1,
    XACT_WAVEBANK_WAVEBANK_BANG3 = 2,
    XACT_WAVEBANK_WAVEBANK_BANG4 = 3,
    XACT_WAVEBANK_WAVEBANK_SPACESHIP_THEME = 4,
} XACT_WAVEBANK_WAVEBANK;

#define XACT_WAVEBANK_WAVEBANK_ENTRY_COUNT 5

#endif // __INCLUDE_WAVEBANK_WAVEBANK__
